name: ci

on: [ push ]

env:
  JAVA_VERSION: 20

jobs:


  Lint:
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - run: ./gradlew lint --stacktrace
        working-directory: Multiplatform-App



  UnitTest:
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - run: ./gradlew check --stacktrace
        working-directory: Multiplatform-App



  Android:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - run: ./gradlew assembleDebug --stacktrace
        working-directory: Multiplatform-App



  Desktop:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - run: ./gradlew :composeApp:jvmJar --stacktrace
        working-directory: Multiplatform-App



  Browser:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - run: ./gradlew :composeApp:jsMainClasses --stacktrace
        working-directory: Multiplatform-App



  iOS:
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: ciIos --stacktrace



  Automation:
    needs: [ Android ]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
    steps:

      - uses: actions/checkout@v3

      - name: Enable KVM group perms
        if: contains(matrix.os, 'ubuntu')
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Install libpulse
        if: contains(matrix.os, 'ubuntu')
        run: |
          sudo apt update
          sudo apt install libpulse-dev

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - uses: gradle/gradle-build-action@v2
        with:
          arguments: ciTest --stacktrace
