name: ci

on: [ push ]

env:
  JAVA_VERSION: 20

jobs:


  Lint:
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - run: ./gradlew lint --stacktrace
        working-directory: Multiplatform-App



  UnitTest:
    runs-on: macos-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - run: ./gradlew check --stacktrace
        working-directory: Multiplatform-App



  Android:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - run: ./gradlew assembleDebug --stacktrace
        working-directory: Multiplatform-App



  Desktop:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - run: ./gradlew :composeApp:jvmJar --stacktrace
        working-directory: Multiplatform-App



  Browser:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ env.JAVA_VERSION }}

      - run: ./gradlew :composeApp:jsMainClasses --stacktrace
        working-directory: Multiplatform-App
